import { Job, Area } from "./type.d";
import { Activity } from "./type";

export const activities: Activity[] = [
  {
    id: 1,
    job: Job.OTPV,
    description:
      "Mantenimiento preventivo de motor principal y revisión de componentes críticos del sistema de transmisión",
    solution: "",
    start_date: "2024-03-14T11:00:00Z",
    end_date: "2024-03-14T13:00:00Z",
    area: Area.MOLINO,
    stop_machine: false,
  },
  {
    id: 2,
    job: Job.OTFM,
    description:
      "Inspección de rodamientos en faja transportadora y ajuste de tensores",
    solution: "",
    start_date: "2024-03-14T14:00:00Z",
    end_date: "2024-03-14T16:00:00Z",
    area: Area.CHANCADO,
    stop_machine: false,
  },
  {
    id: 3,
    job: Job.OTCO,
    description: "Corrección de fuga en sistema hidráulico",
    solution: "Se reemplazó O-ring y se ajustó la presión",
    start_date: "2024-03-14T16:30:00Z",
    end_date: "2024-03-14T18:00:00Z",
    area: Area.PLANTA_GENERAL,
    stop_machine: true,
  },
  {
    id: 4,
    job: Job.OTPD,
    description: "Reparación de sistema de control de temperatura",
    solution: "Se reemplazó el sensor de temperatura y se ajustó la presión",
    start_date: "2024-03-14T18:30:00Z",
    end_date: "2024-03-14T20:00:00Z",
    area: Area.CHANCADO,
    stop_machine: true,
  },
  {
    id: 5,
    job: Job.OTEM,
    description: "Reparación de sistema de control de presión",
    solution: "Se reemplazó el sensor de presión y se ajustó la presión",
    start_date: "2024-03-14T20:30:00Z",
    end_date: "2024-03-14T22:00:00Z",
    area: Area.CHANCADO,
    stop_machine: true,
  },
  {
    id: 6,
    job: Job.OTPD,
    description: "Reparación de sistema de control de temperatura",
    solution: "Se reemplazó el sensor de temperatura y se ajustó la presión",
    start_date: "2024-03-14T22:30:00Z",
    end_date: "2024-03-14T23:00:00Z",
    area: Area.CHANCADO,
    stop_machine: true,
  },
  {
    id: 7,
    job: Job.OTEM,
    description: "Reparación de sistema de control de presión",
    solution: "Se reemplazó el sensor de presión y se ajustó la presión",
    start_date: "2024-03-14T23:30:00Z",
    end_date: "2024-03-15T07:30:00Z",
    area: Area.CHANCADO,
    stop_machine: true,
  },
  {
    id: 8,
    job: Job.OTPV,
    description: "Arreglo",
    solution: "Arreglarlo",
    start_date: "2024-03-15T02:30:00Z",
    end_date: "2024-03-15T03:00:00Z",
    area: Area.COMPRESORA_NORTE,
    stop_machine: false,
  },
];
